""" Branch structure examples """
# params = {
#     'shape' : 4,
#     'g_scale' : 1,
#     'g_scale_v' : 0,
#     'levels' : 1,
#     'ratio' : 0.03,
#     'ratio_power' : 1.1,
#     'flare' : 0,
#     'base_size' :     [0,   0.02,   0.02, 0.02],
#     'down_angle' :    [-0,    70,     45,     45],
#     'down_angle_v' :  [-0,    0,    10,     10],
#     'rotate' :        [-0,    -90,    140,    77],
#     'rotate_v' :      [-0,    0,      0,       0],
#     'branches' :      [-0,    0,     30,     10],
#     'length' :        [1,     0.3,    0.6,     0],
#     'length_v' :      [0,     0,      0,       0],
#     'taper' :         [1,     1,      1,       1],
#     'seg_splits' :    [1,     0,      0,       0],
#     'split_angle' :   [-40,     0,      0,       0],
#     'split_angle_v' : [0,     0,      0,       0],
#     'curve_res' :     [5,     1,      3,       1],
#     'curve' :         [0,     0,    0,     0],
#     'curve_back' :    [0,     0,      0,       0],
#     'curve_v' :       [0,     0,     0,      0],
#     'bend_v' :        [-0,    0,     0,       0],
#     'branch_dist' :   [-0,    0,      0,       0],
#     'leaf_blos_num' : 0,
#     'tropism' : [0, 0, 0]
# }

params = {
    'shape' : 4,
    'g_scale' : 1,
    'g_scale_v' : 0,
    'levels' : 2,
    'ratio' : 0.03,
    'ratio_power' : 1,
    'flare' : 0,
    'base_size' :     [0,   0.02,   0.02, 0.02],
    'down_angle' :    [-0,    70,     45,     45],
    'down_angle_v' :  [-0,    0,    10,     10],
    'rotate' :        [-0,    -90,    140,    77],
    'rotate_v' :      [-0,    0,      0,       0],
    'branches' :      [-0,    6,     30,     10],
    'length' :        [1,     0.3,    0.6,     0],
    'length_v' :      [0,     0,      0,       0],
    'taper' :         [1,     1,      1,       1],
    'seg_splits' :    [0,     0,      0,       0],
    'split_angle' :   [0,     0,      0,       0],
    'split_angle_v' : [0,     0,      0,       0],
    'curve_res' :     [10,     1,      3,       1],
    'curve' :         [0,     0,    0,     0],
    'curve_back' :    [0,     0,      0,       0],
    'curve_v' :       [0,     0,     0,      0],
    'bend_v' :        [-0,    0,     0,       0],
    'branch_dist' :   [-0,    0,      0,       0],
    'leaf_blos_num' : 0,
    'tropism' : [0, 0, 0]
}



#
# """ Branch structure examples """
# params = {
#     'shape' : 4,
#     'g_scale' : 1,
#     'g_scale_v' : 0,
#     'levels' : 2,
#     'ratio' : 0.02,
#     'ratio_power' : 1.2,
#     'flare' : 0,
#     'base_size' :     [0.5,   0.02,   0.02, 0.02],
#     'down_angle' :    [-0,    70,     45,     45],
#     'down_angle_v' :  [-0,    0,    10,     10],
#     'rotate' :        [-0,    140,    140,    77],
#     'rotate_v' :      [-0,    0,      0,       0],
#     'branches' :      [-0,    4,     30,     10],
#     'length' :        [1,     0.3,    0.6,     0],
#     'length_v' :      [0,     0,      0,       0],
#     'taper' :         [0,     1,      1,       1],
#     'seg_splits' :    [0,     0,      0,       0],
#     'split_angle' :   [0,     0,      0,       0],
#     'split_angle_v' : [0,     0,      0,       0],
#     'curve_res' :     [1,     1,      3,       1],
#     'curve' :         [0,     0,    0,     0],
#     'curve_back' :    [0,     0,      0,       0],
#     'curve_v' :       [0,    0,     0,      0],
#     'bend_v' :        [-0,    0,     0,       0],
#     'branch_dist' :   [-0,    0,      0,       0],
#     'leaf_blos_num' : 0,
#     'tropism' : [0, 0, 0]
# }
#
